Repository josemarluedke/glimmer-apollo, pull requests merged in 2021-06, with the labels that each got.

#19 typo(README): fix two grammar issues
  README.md
Labels: Type: Documentation

#20 GlimmerX refactor example setup to use provider
  examples/glimmerx/src/apollo.ts
  examples/glimmerx/src/index.ts
  examples/glimmerx/tests/rendering/App.test.js
  examples/glimmerx/tests/util.ts
Labels: Type: Internal

#21 Refactor setClient/getClient and others to use owner as a context
  README.md
  examples/glimmerx/src/apollo.ts
  packages/glimmer-apollo/src/-private/client.ts
  packages/glimmer-apollo/src/-private/mutation.ts
  packages/glimmer-apollo/src/-private/query.ts
  packages/glimmer-apollo/src/environment-ember.ts
  packages/glimmer-apollo/src/environment.ts
  packages/glimmer-apollo/src/index.ts
  packages/test-app/app/instance-initializers/apollo.ts
  packages/test-app/tests/unit/client-test.ts
  packages/test-app/tests/unit/mutation-test.ts
  packages/test-app/tests/unit/query-test.ts
Labels: Type: Breaking Change

#22 Re-export gql from apollo client
  README.md
  examples/glimmerx/src/Notes.ts
  packages/glimmer-apollo/package.json
  packages/glimmer-apollo/src/index.ts
  packages/test-app/app/components/playground/experiment.ts
  packages/test-app/package.json
  packages/test-app/tests/unit/mutation-test.ts
  packages/test-app/tests/unit/query-test.ts
  yarn.lock
Labels: Type: Enhancement

#23 Add docs for intro, getting started, fetching (queries and mutations)
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/fetching/mutations.md
  docs/fetching/queries.md
  docs/fetching/subscriptions.md
  docs/getting-started.md
  examples/glimmerx/README.md
  examples/glimmerx/src/App.ts
  examples/glimmerx/src/CreateNote.ts
  examples/glimmerx/src/Notes.ts
  examples/glimmerx/src/TutorialNotes.ts
  examples/glimmerx/src/index.ts
  examples/glimmerx/src/mock/factories.ts
  examples/glimmerx/src/mock/schema.graphql
  examples/glimmerx/src/mutations.ts
  examples/glimmerx/src/queries.ts
  packages/glimmer-apollo/src/-private/observable.ts
  packages/test-app/README.md
  packages/test-app/app/templates/application.hbs
  packages/test-app/tests/unit/query-test.ts
Labels: Type: Documentation

#27 Add clientId option to useQuery and useMutation
  packages/glimmer-apollo/src/-private/mutation.ts
  packages/glimmer-apollo/src/-private/query.ts
  packages/test-app/tests/unit/mutation-test.ts
  packages/test-app/tests/unit/query-test.ts
Labels: Type: Enhancement

#28 Add Docs Site
  package.json
  site/.docfy-config.js
  site/.editorconfig
  site/.ember-cli
  site/.template-lintrc.js
  site/.watchmanconfig
  site/README.md
  site/app/app.js
  site/app/components/.gitkeep
  site/app/components/glimmer-apollo-logo.hbs
  site/app/controllers/.gitkeep
  site/app/helpers/.gitkeep
  site/app/index.html
  site/app/models/.gitkeep
  site/app/router.js
  site/app/routes/.gitkeep
  site/app/routes/application.js
  site/app/routes/index.js
  site/app/styles/app.css
  site/app/styles/highlight.css
  site/app/templates/application.hbs
  site/app/templates/docs.hbs
  site/app/templates/index.hbs
  site/config/ember-cli-update.json
  site/config/environment.js
  site/config/optional-features.json
  site/config/targets.js
  site/ember-cli-build.js
  site/package.json
  site/public/assets/favicons/android-chrome-192x192.png
  site/public/assets/favicons/android-chrome-512x512.png
  site/public/assets/favicons/apple-touch-icon.png
  site/public/assets/favicons/favicon-16x16.png
  site/public/assets/favicons/favicon-32x32.png
  site/public/assets/favicons/favicon.ico
  site/public/assets/favicons/site.webmanifest
  site/public/assets/images/og-image.jpg
  site/public/robots.txt
  site/tailwind.config.js
  site/testem.js
  site/tests/helpers/.gitkeep
  site/tests/index.html
  site/tests/integration/.gitkeep
  site/tests/test-helper.js
  site/tests/unit/.gitkeep
  site/tests/unit/routes/index-test.js
  site/vendor/.gitkeep
  yarn.lock
Labels: Type: Documentation

#29 documentation: fix typo: seMutation -> useMutation
  docs/fetching/mutations.md
Labels: Type: Documentation
